update 06-08-2017
jakwuh/dailytip pull request #4
Opened 2017-08-08 16:20 UTC by Drapegnik

2017-08-08 20:10 UTC, jakwuh requested changes

2017-08-08 20:10 UTC, jakwuh commented on tips/06-08-2017/React.xml
> +</templateSet>
missing line break

2017-08-08 20:10 UTC, jakwuh commented on tips/06-08-2017/Readme.md
> -#### Subscribe to our [Telegram channel](https://t.me/dailytip) to get daily updates
Removing subscribe teaser? Why?

2017-08-08 20:10 UTC, jakwuh commented on tips/06-08-2017/Readme.md
> +<p align="center">
Setting [width=700] will create inconveniences for mobile readers. This should be:
```![live template demo](http://res.cloudinary.com/dzsjwgjii/image/upload/v1502207798/rcc-demo.gif)```

2017-08-08 20:10 UTC, jakwuh commented on tips/06-08-2017/Readme.md
> -Special credits to [@drapegnik](https://github.com/Drapegnik) for a useful set of live templates.
Removing footer teaser? Why?

2017-08-09 10:31 UTC, Drapegnik commented on tips/06-08-2017/React.xml
> +</templateSet>
this file is generated by WebStorm, are you sure it's needed to fix it every time?

2017-08-09 10:40 UTC, Drapegnik commented on tips/06-08-2017/Readme.md
> -#### Subscribe to our [Telegram channel](https://t.me/dailytip) to get daily updates
oh, sorry, it's accidently due to copy pasting 😮

2017-08-11 11:28 UTC, Drapegnik commented
@jakwuh, hey!

2017-08-11 21:03 UTC, jakwuh commented
Sorry for a small delay :) Thank you for updating your PR 👍

2017-08-11 21:03 UTC, merged